
sources:
  - name: CMS
    handler:
      graphql:
        endpoint: https://sushi-strapi-cms.herokuapp.com/graphql

documents:
  - ./query.graphql

# sdk:
#   generateOperations:
#     selectionSetDepth: 2
