sources:
  - name: Exchange
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:sushiswap/exchange-ethereum}
  # - name: Staking
  #   handler:
  #     graphql:
  #       endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:olastenberg/staking-arbitrum}

additionalTypeDefs: |
  extend type Pair {
    chainId: BigInt!
    chainName: String!
  }
  extend type Bundle {
    chainId: BigInt!
    chainName: String!
  }
  extend type Query {
    crossChainPairs(first: Int!, chainIds: [BigInt!]!): [Pair!]!
    crossChainBundles(first: Int!, chainIds: [BigInt!]!): [Bundle!]!
  }

additionalResolvers:
  - ./resolvers.ts

documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { chainId: string; chainName: string; subgraphName: string; subgraphHost: string }'