sources:
  - name: Exchange
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:sushiswap/sushiswap-avalanche}
  - name: Trident
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:sushiswap/trident-optimism}

additionalTypeDefs: |
  input Pagination {
    pageIndex: Int! = 0
    pageSize: Int! = 20
  }
  type RewardToken {
    address: String!
    symbol: String!
    decimals: Int!
  }
  type Incentive {
    apr: BigDecimal!
    rewardPerDay: BigDecimal!
    rewardToken: RewardToken!
    rewarderAddress: String!
    rewarderType: String!
  }
  type Farm {
    id: ID!
    feeApy: BigDecimal!
    incentives: [Incentive!]!
    chefType: String!
    poolType: String!
  }
  extend type Factory {
    chainId: BigInt!
    chainName: String!
    chainShortName: String!
  }
  extend type Pair {
    chainId: BigInt!
    chainName: String!
    chainShortName: String!
    volume24h: BigDecimal!
    volume7d: BigDecimal!
    fees24h: BigDecimal!
    fees7d: BigDecimal!
    farm: Farm
    incentiveApr: BigDecimal!
    feeApr: BigDecimal!
  }
  extend type FactoryDaySnapshot {
    chainId: BigInt!
    chainName: String!
    chainShortName: String!
  }
  extend type Query {
    crossChainPairs(
      first: Int!,
      skip: Int! = 0, 
      pagination: Pagination,
      where: Pair_filter, 
      orderBy: Pair_orderBy, 
      orderDirection: OrderDirection, 
      chainIds: [BigInt!]!, 
      now: Int!,
      block: Block_height
    ): [Pair!]!
    crossChainStats(first: Int!, orderBy: Pair_orderBy, orderDirection: OrderDirection, chainIds: [BigInt!]!, now: Int!): [Pair!]!
    crossChainFactoryDaySnapshots(first: Int! = 1000, skip: Int! = 0, where: FactoryDaySnapshot_filter, orderBy: FactoryDaySnapshot_orderBy!, orderDirection: OrderDirection!, block: Block_height, chainIds: [BigInt!]!): [FactoryDaySnapshot!]!
    crossChainFactories(chainIds: [BigInt!]!): [Factory!]!
  }

additionalResolvers:
  - ./resolvers.ts

documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { chainId: string; chainName: string; chainShortName: string; subgraphName: string; subgraphHost: string }'
