sources:
  - name: Exchange
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:sushiswap/exchange}
    transforms:
      - addSourceName: true
      - autoPagination:
          validateSchema: true

documents:
  - ./query.graphql