sources:
  - name: Trident
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com/subgraphs/name}/{context.subgraphName:olastenberg/trident-optimism}
    transforms:
      # - blockTracking:
      #     validateSchema: true
      - autoPagination:
          validateSchema: true
  - name: Exchange
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com/subgraphs/name}/{context.subgraphName:sushiswap/exchange-ethereum}
    transforms:
      # - blockTracking:
      #     validateSchema: true
      - autoPagination:
          validateSchema: true
      - filterSchema:
          mode: wrap
          filters:
            - Type.!{Factory}
documents:
  - ./query.graphql