sources:
  - name: Trident
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/olastenberg/trident-optimism
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
  - name: Exchange
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sushiswap/exchange-ethereum
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
      - filterSchema:
          mode: wrap
          filters:
            - Type.!{Factory}
documents:
  - ./query.graphql