sources:
  - name: ExchangeDummy
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sushiswap/exchange-ethereum
  - name: Exchange
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sushiswap/exchange-ethereum
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
documents:
  - ./query.graphql