sources:
  - name: furostream_kovan
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/olastenberg/furostream-kovan
  - name: furovesting_kovan
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/olastenberg/furovesting-kovan
    transforms:
      - rename:
          mode: wrap
          renames:
            - from:
                type: Transaction
              to:
                type: VestingTransaction
            - from:
                type: Query
                field: transaction
              to:
                type: Query
                field: vestingTransaction
            - from:
                type: Query
                field: transactions
              to:
                type: Query
                field: vestingTransactions
            - from:
                type: Furo
              to:
                type: FuroVesting
            - from:
                type: Query
                field: furo
              to:
                type: Query
                field: furoVesting
            - from:
                type: Token
              to:
                type: VestingToken
            - from:
                type: User
              to:
                type: VestingUser
            - from:
                type: Query
                field: user
              to:
                type: Query
                field: vestingUser

            - from:
                type: Query
                field: users
              to:
                type: Query
                field: vestingUsers
documents:
  - ./query.graphql