sources:
  - name: furostream_kovan
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/olastenberg/furostream-kovan
  # - name: furovesting_kovan
  #   handler:
  #     graphql:
  #       endpoint: https://api.thegraph.com/subgraphs/name/olastenberg/furovesting-kovan
documents:
  - ./query.graphql