sources:
  - name: FuroStream
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/subgraphs/name/{context.name:olastenberg/furo-ethereum}
    transforms:
      - autoPagination:
          validateSchema: true


documents:
  - ./query.graphql